// Generated by CoffeeScript 1.6.3
(function() {
  var Code, coffee, fs;

  fs = require('fs');

  coffee = require('coffee-script');

  module.exports = {
    filter: function(source) {
      var code;
      code = new Code(source);
      return console.log(code.filter());
    },
    find: function() {}
  };

  Code = (function() {
    function Code(source) {
      this.tokens = coffee.tokens(source);
    }

    Code.prototype.filter = function() {
      return this.tokens.filter(function(el, i, arr) {
        return el[0] === 'HERECOMMENT' && el[1].charAt(0) === '*';
      });
    };

    return Code;

  })();

}).call(this);
