// Generated by CoffeeScript 1.6.3
(function() {
  var Code, Token, coffee, fs;

  fs = require('fs');

  coffee = require('coffee-script');

  module.exports = {
    filter: function(source) {
      var code;
      code = new Code(source);
      return code.filterJSDocs();
    },
    find: function() {}
  };

  Code = (function() {
    function Code(source) {
      this.tokens = coffee.tokens(source).map(function(el) {
        return new Token(el);
      });
    }

    Code.prototype.filterJSDocs = function() {
      var _this = this;
      return this.tokens.filter(function(token) {
        if (!(token.type === 'HERECOMMENT' && token.source.charAt(0) === '*')) {
          return;
        }
        console.log(token.toString());
        return console.log(_this.filterAt(token.range.last_line + 1));
      });
    };

    Code.prototype.filterAt = function(line) {
      return this.tokens.filter(function(token) {
        return token.range.first_line === line;
      });
    };

    return Code;

  })();

  Token = (function() {
    function Token(_arg) {
      this.type = _arg[0], this.source = _arg[1], this.range = _arg[2], this.newLine = _arg[3];
      if (this.newLine == null) {
        this.newLine = false;
      }
    }

    Token.prototype.toString = function() {
      return "[" + this.type + "] " + (('' + this.source).replace(/\n/g, '\\n'));
    };

    return Token;

  })();

}).call(this);
