// Generated by CoffeeScript 1.6.3
(function() {
  var ClassDoc, Code, Doc, Param, Renderer, Token, coffee, fs,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  fs = require('fs');

  coffee = require('coffee-script');

  module.exports = {
    parse: function(source) {
      var code;
      code = new Code(source);
      return code.filterJSDocs();
    },
    render: function(engine, options) {
      var renderer;
      if (engine == null) {
        engine = 'ejs';
      }
      if (options == null) {
        options = {};
      }
      return renderer = new Renderer(engine, options);
    }
  };

  Renderer = (function() {
    function Renderer() {
      var engine;
      engine = require(engine);
      engine.render(template, options);
    }

    return Renderer;

  })();

  Code = (function() {
    function Code(source) {
      this.tokens = coffee.tokens(source).map(function(el) {
        return new Token(el);
      });
    }

    Code.prototype.filterJSDocs = function() {
      var classDoc, classIndent, docs, indent,
        _this = this;
      docs = [];
      indent = 0;
      classIndent = null;
      classDoc = null;
      this.tokens.filter(function(token) {
        var doc, isParam, isParamValue, names, param;
        switch (token.type) {
          case 'INDENT':
            indent += token.source;
            break;
          case 'OUTDENT':
            indent -= token.source;
            if ((classIndent != null) && classIndent === indent) {
              classDoc = classDoc.fixName();
              docs.push(classDoc);
              classDoc = null;
              classIndent = null;
            }
            break;
          case 'HERECOMMENT':
            if (token.source.charAt(0) !== '*') {
              return;
            }
            doc = new Doc(token.source);
            param = null;
            names = [];
            isParam = false;
            isParamValue = false;
            return _this.filterAt(token.range.last_line + 1).forEach(function(relatedToken) {
              var source, type;
              type = relatedToken.type, source = relatedToken.source;
              switch (type) {
                case 'CLASS':
                  classDoc = doc = new ClassDoc(doc.description);
                  classDoc.type = type;
                  return classIndent = indent;
                case '@':
                  return doc.modifier = 'static';
                case 'IDENTIFIER':
                  if (isParam) {
                    param = new Param(source);
                    return doc.pushParam(param);
                  } else {
                    return names != null ? names.push(source) : void 0;
                  }
                  break;
                case '.':
                  return names != null ? names.push(source) : void 0;
                case '=':
                  if (isParam) {
                    return isParamValue = true;
                  } else {
                    doc.name = names.join('');
                    names = null;
                    docs.push(doc);
                  }
                  break;
                case ':':
                  if (isParam) {
                    return;
                  }
                  doc.name = names.join('');
                  names = null;
                  if (classDoc != null) {
                    if (doc.modifier === 'static') {
                      return classDoc.pushStatic(doc);
                    } else {
                      doc.modifier = 'member';
                      return classDoc.pushMember(doc);
                    }
                  } else {
                    return docs.push(doc);
                  }
                  break;
                case 'PARAM_START':
                  return isParam = true;
                case 'PARAM_END':
                  return isParam = false;
                case '->':
                case '=>':
                  doc.type = 'function';
                  return '';
                default:
                  if (isParamValue) {
                    isParamValue = false;
                    switch (type) {
                      case 'NUMBER':
                        source = parseFloat(source);
                    }
                    return param.value = source;
                  }
              }
            });
        }
      });
      return docs;
    };

    Code.prototype.filterAt = function(line) {
      return this.tokens.filter(function(token) {
        return token.range.first_line === line;
      });
    };

    return Code;

  })();

  Token = (function() {
    function Token(_arg) {
      this.type = _arg[0], this.source = _arg[1], this.range = _arg[2], this.newLine = _arg[3];
      if (this.newLine == null) {
        this.newLine = false;
      }
    }

    Token.prototype.toString = function() {
      return "[" + this.type + "] " + (('' + this.source).replace(/\n/g, '\\n'));
    };

    return Token;

  })();

  Doc = (function() {
    function Doc(description) {
      if (description == null) {
        description = '';
      }
      this.type = 'variable';
      this.description = description.replace(/^\*\s*(.*?)\s*$/, '$1');
    }

    Doc.prototype.pushParam = function() {
      if (this.params == null) {
        this.params = [];
      }
      return this.params.push.apply(this.params, arguments);
    };

    return Doc;

  })();

  ClassDoc = (function(_super) {
    __extends(ClassDoc, _super);

    function ClassDoc(description) {
      this.description = description != null ? description : '';
      ClassDoc.__super__.constructor.call(this, this.description);
      this.statics = [];
      this.members = [];
    }

    ClassDoc.prototype.pushStatic = function() {
      return this.statics.push.apply(this.statics, arguments);
    };

    ClassDoc.prototype.pushMember = function() {
      return this.members.push.apply(this.members, arguments);
    };

    return ClassDoc;

  })(Doc);

  Param = (function() {
    function Param(name, value) {
      this.name = name;
      this.value = value != null ? value : null;
    }

    return Param;

  })();

}).call(this);
